### PR TITLE
Teleport optimization

### PR DESCRIPTION
**Pull request by wysohn**
This is one possible solution for the theory I threw last time.

I will use it for my server, but you might find it useful too.

### CODE REVIEW

**Comment by Phoenix616** [comment]
Definitely an interesting approach. I would prefer it 'though if you used the Bukkit scheduler api instead of starting your own thread. Especially as you seem to access the Bukkit api on it which can lead to issues when not done on the main thread.

**Comment by wysohn** [comment]
Yup, totally agree.

Would be really nice if bukkit was multi-threaded!

**Comment by wysohn** [comment]
RandomTeleport v1.7.4 (manually compiled)Total: 0.062 s Pct: 0.11%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
       0.11%	   0.22%	  0.06 s	     0.11 ms	 1.0	       0.6k	    Task: RandomTeleport$1(interval 1)

it takes about 8~10 seconds before actual teleport happens; I think it's not a bad trade for saving CPU resource.

Obviously it will take more time if more players try to rtp at the same time, but it's pretty bearable.

Or adding 1~3 more scheduler to work on the task can speed up, yet the bukkit thread will suffer from it.

**Comment by Phoenix616** [comment]
Please make sure to follow the general project code formatting of using 4 spaces for indentation. (Instead of tabs) It looks a bit messy right now.

You should also use a configured message on line 613 on RandomTeleport.java, not sure why you commented that addition out again.

**Comment by wysohn** [comment]
oh, that's why my codes are all messy. I changed the editor setting now.

I commented that out as I don't know how exactly it works.

does it generate the configured message automatically?

**Comment by Phoenix616** [comment]
You have to add the language key to the `msg` section in the config.yml.

**Comment by wysohn** [comment]
Hi! I added that to the config.yml, but it seems the new message is not automatically added to the existing config.yml.

was it intended? or did I do something wrong?

**Pull request closed without merging**
